### ISSUE TITLE
Segmentation fault during https request

### ISSUE THREAD

**Issue by m3ngzhang** [apache/teaclave-sgx-sdk#221] opened 2020-04-08 11:45 UTC
My code is like below. I am trying to send https request from enclave. I think that should have worked, but it just gives me segmentation fault error. How should I fix it?
#[no_mangle]
pub extern "C" fn send_http_request(hostname: *const c_char) -> sgx_status_t {
    println!("1");
    let hostname = unsafe { CStr::from_ptr(hostname).to_str() };
    let hostname = hostname.expect("Failed to recover hostname");

    println!("hostname: {:?}", hostname);

    let mut writer = Vec::new(); //container for body of a response
    let res = request::get("https://www.baidu.com", &mut writer).unwrap();

    println!("Status: {} {}", res.status_code(), res.reason());
    println!("{:?}", res);

    sgx_status_t::SGX_SUCCESS
}

**Comment by dingelish** [comment] 2020-04-08 22:13
duplicate of #220 

You may refer to [http_req](../tree/master/samplecode/http_req) sample.

**Closed as completed by dingelish** 2020-04-08 22:13 UTC
